version: '3.6'
services:
  web:
    container_name: tre-web
    build: .
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/db?serverVersion=15&charset=utf8"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "php bin/console doctrine:migrations:migrate --no-interaction && symfony serve --no-tls"
  cron:
    container_name: tre-cron
    build: .
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/db?serverVersion=15&charset=utf8"
    depends_on:
      db:
        condition: service_healthy
    command: bin/update.sh
  db:
    container_name: tre-db
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U user -d db
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
